"""
GO Term Group Assigner
=======================
Assigns each GO term in your dataset to exactly ONE group using
a strict "most specific ancestor" rule.

How the assignment rule works:
    A GO term may have ancestors in multiple top-level groups (because GO is a DAG).
    To avoid overlap, we assign each term to the group whose root is the SMALLEST
    (most specific / deepest in hierarchy). This means we always prefer the more
    precise biological category over a broader one.

Usage:
    1. Make sure go_dict.json is in the same directory (generated by go_parser.py)
    2. Set DATASET_PATH and GO_COL_IDX below
    3. Run: python go_group_assigner.py
"""

import json
from collections import defaultdict


# ── CONFIG ─────────────────────────────────────────────────────────────────────
GO_DICT_PATH = "C:/Users/USER/Documents/cod3astro/ML_AI/NeuralProt/data/processed/go_dict.json"
DATASET_PATH = "C:/Users/USER/Documents/cod3astro/ML_AI/NeuralProt/data/raw/uniprotkb_AND_reviewed_true_AND_protein_2025_12_27.tsv"
GO_COL_IDX   = 5    # zero-based column index for GO terms in the TSV — adjust if your file differs


# ── GROUP DEFINITIONS ──────────────────────────────────────────────────────────
# These are your candidate groups identified from the parser output.
# Each entry maps a human-readable group name to its GO root term ID.
#
# The root ID is what we check in the ancestor cache — if a GO term has this
# root anywhere in its ancestor set, it belongs to that group.
#
# Groups marked "large" will likely need further splitting before training.
# Groups marked "small" may need merging with a related group.

TARGET_GROUPS = {
    # --- Large groups — too many terms to train as-is, will need sub-grouping ---
    "cellular_process":              "GO:0009987",
    "biological_regulation":         "GO:0065007",
    "catalytic_activity":            "GO:0003824",
    "developmental_process":         "GO:0032502",
    "protein_containing_complex":    "GO:0032991",
    "cellular_anatomical_structure": "GO:0110165",
    "response_to_stimulus":          "GO:0050896",
    "binding":                       "GO:0005488",
    "multicellular_organismal":      "GO:0032501",

    # --- Well-sized groups — primary candidates for training ---
    "localization":                  "GO:0051179",
    "transporter_activity":          "GO:0005215",
    "immune_system_process":         "GO:0002376",
    "molecular_transducer":          "GO:0060089",
    "reproductive_process":          "GO:0022414",
    "interspecies_interaction":      "GO:0044419",

    # --- Smaller groups — might need merging depending on assigned term counts ---
    "atp_dependent_activity":        "GO:0140657",
    "homeostatic_process":           "GO:0042592",
    "mf_regulator_activity":         "GO:0098772",
    "growth":                        "GO:0040007",
    "viral_process":                 "GO:0016032",
    "molecular_adaptor_activity":    "GO:0060090",
}
# ───────────────────────────────────────────────────────────────────────────────


def load_go_dict(path):
    """
    Load the pre-parsed go_dict from the JSON file produced by go_parser.py.
    We do this instead of re-parsing the OBO file every time — the parser
    already did the heavy lifting and saved the result.
    """
    print(f"Loading go_dict from {path} ...")
    with open(path, "r") as f:
        go_dict = json.load(f)
    print(f"Loaded {len(go_dict):,} GO terms from file")
    return go_dict


def build_ancestor_cache(go_dict):
    """
    Pre-compute the full ancestor set for every GO term.

    Same logic as in go_parser.py — we need this here because the saved
    go_dict.json doesn't include the ancestor cache (it'd be massive).
    We rebuild it in memory each run. Takes ~10-30 seconds.

    The inner function is defined here so it can close over `cache`
    without needing to pass it as an argument every recursive call.
    """
    print("Rebuilding ancestor cache from go_dict — this takes ~10-30 seconds...")

    cache = {}

    def get_ancestors(go_id):
        if go_id in cache:
            return cache[go_id]   # already computed, skip

        ancestors = set()
        term = go_dict.get(go_id)

        if term:
            for parent in term.get("parents", []):
                ancestors.add(parent)
                ancestors.update(get_ancestors(parent))   # climb the tree

        cache[go_id] = ancestors
        return ancestors

    for go_id in go_dict:
        get_ancestors(go_id)

    print(f"Ancestor cache ready — {len(cache):,} terms covered")
    return cache


def get_group_sizes(go_dict, ancestor_cache, target_groups):
    """
    Count how many terms in go_dict fall under each target group root.

    This is the "full ontology size" of each group — not just what's in
    the dataset. We use this as the tiebreaker when a GO term belongs to
    multiple groups: the smallest group wins because it's the most specific
    biological classification.
    """
    print("Counting the full ontology size of each group (used for tiebreaking)...")
    sizes = {}

    for group_name, group_root in target_groups.items():
        count = sum(
            1 for go_id in go_dict
            if group_root in ancestor_cache.get(go_id, set())
        )
        sizes[group_name] = count
        print(f"  {group_name:<35} {count:>6,} terms in full ontology")

    return sizes


def read_dataset_go_terms(dataset_path, go_col_idx, go_dict):
    """
    Pull out every GO term that appears in the dataset and also exists in go_dict.

    We only keep terms that are in go_dict — anything else is either obsolete
    or an alternate ID that wasn't resolved by the parser, and we can't assign
    it to a group anyway.
    """
    print(f"\nReading dataset from {dataset_path} ...")
    dataset_go_terms = set()
    rows_read = 0
    rows_skipped = 0

    with open(dataset_path, "r", encoding="utf-8") as f:
        for line in f:
            if line.startswith("#") or not line.strip():
                continue   # comment or blank line — skip

            parts = line.strip().split("\t")
            if len(parts) <= go_col_idx:
                rows_skipped += 1
                continue   # row doesn't reach the GO column — probably a header or malformed row

            rows_read += 1
            raw_ids = parts[go_col_idx].split(";")

            for raw in raw_ids:
                raw = raw.strip()
                if raw in go_dict:
                    dataset_go_terms.add(raw)

    print(f"Read {rows_read:,} protein rows ({rows_skipped} skipped — wrong column count)")
    print(f"Found {len(dataset_go_terms):,} unique GO terms that exist in go_dict")

    if len(dataset_go_terms) < 500:
        print("WARNING: very few GO terms found — is GO_COL_IDX set correctly?")
        print(f"         Currently looking at column index {go_col_idx} (zero-based)")

    return dataset_go_terms


def assign_go_terms(dataset_go_terms, ancestor_cache, target_groups, group_sizes):
    """
    Assign each dataset GO term to exactly one group.

    The rule:
      - Find all groups this term belongs to (i.e., whose root appears in its ancestors).
      - If it belongs to only one group, easy — assign it there.
      - If it belongs to multiple groups (because GO is a DAG, not a tree),
        assign it to the group with the SMALLEST full ontology size.
        Smaller = more specific = better biological fit.

    Terms that don't match any group root in their ancestor set are left unassigned.
    These are usually root-level terms like "biological_process" itself — too general
    to be meaningful labels for training.
    """
    print("\nAssigning each dataset GO term to exactly one group...")

    assignment  = {}   # go_id → group_name
    unassigned  = set()
    multi_match = 0    # just tracking how often the tiebreaker fires

    for go_id in dataset_go_terms:
        ancestors = ancestor_cache.get(go_id, set())

        # Which groups does this term belong to?
        matched_groups = [
            group_name
            for group_name, group_root in target_groups.items()
            if group_root in ancestors
        ]

        if not matched_groups:
            # No group claimed this term — it's either a root itself or sits above all groups
            unassigned.add(go_id)
            continue

        if len(matched_groups) == 1:
            assignment[go_id] = matched_groups[0]
        else:
            # Multiple groups matched — pick the most specific one (smallest group)
            best = min(matched_groups, key=lambda g: group_sizes.get(g, float("inf")))
            assignment[go_id] = best
            multi_match += 1

    print(f"Assignment complete:")
    print(f"  {len(assignment):,} terms assigned to a group")
    print(f"  {len(unassigned):,} terms left unassigned (roots or above all group boundaries)")
    print(f"  {multi_match:,} terms needed the tiebreaker (belonged to multiple groups)")

    return assignment, unassigned


def report(assignment, unassigned, group_sizes, target_groups):
    """
    Print a readable summary showing how many terms landed in each group,
    and what we recommend doing with each group based on size.

    Thresholds are rough guidelines based on what we've seen work:
      500+  terms → too big to train as one model, needs splitting
      150+  terms → good size, train as-is
      50+   terms → smallish, consider merging with something related
      <50   terms → too small to learn from reliably, skip or merge
    """
    group_counts = defaultdict(int)
    for go_id, group in assignment.items():
        group_counts[group] += 1

    print("\n── Group Assignment Results ─────────────────────────────────────")
    print(f"  {'Group':<35} {'GO Root':<15} {'Full Size':>9}  {'Assigned':>8}  Recommendation")
    print(f"  {'-'*34} {'-'*14} {'-'*9}  {'-'*8}  {'-'*20}")

    recommendations = []
    for group_name, group_root in sorted(target_groups.items(), key=lambda x: -group_counts.get(x[0], 0)):
        assigned  = group_counts.get(group_name, 0)
        full_size = group_sizes.get(group_name, 0)

        if assigned >= 500:
            rec = "SPLIT FURTHER"
        elif assigned >= 150:
            rec = "GOOD TO TRAIN"
        elif assigned >= 50:
            rec = "SMALL — consider merging"
        else:
            rec = "TOO SMALL — skip or merge"

        print(f"  {group_name:<35} {group_root:<15} {full_size:>9,}  {assigned:>8,}  {rec}")
        recommendations.append((group_name, assigned, rec))

    print(f"\n  Total assigned : {len(assignment):,} GO terms")
    print(f"  Unassigned     : {len(unassigned):,} GO terms")

    # Break down what's actionable
    trainable   = [g for g, a, r in recommendations if "GOOD TO TRAIN" in r]
    needs_split = [g for g, a, r in recommendations if "SPLIT" in r]
    too_small   = [g for g, a, r in recommendations if "TOO SMALL" in r]

    print(f"\n── Summary ──────────────────────────────────────────────────────")
    print(f"  Ready to train    : {len(trainable)} groups")
    for g in trainable:
        print(f"    - {g}")
    print(f"  Need splitting    : {len(needs_split)} groups")
    for g in needs_split:
        print(f"    - {g}")
    print(f"  Too small / merge : {len(too_small)} groups")
    for g in too_small:
        print(f"    - {g}")


def save_assignment(assignment, unassigned, path="C:/Users/USER/Documents/cod3astro/ML_AI/NeuralProt/data/processed/go_group_assignment_v1_deprecated.json"):
    """
    Save the final go_id → group mapping to JSON.

    The output is structured as group → [list of GO term IDs] so the
    data processor can iterate over groups directly without inverting the map.
    The unassigned terms are saved too for bookkeeping — the paper documents
    their count for transparency.
    """
    # Flip the assignment dict so it groups by group name
    group_to_terms = defaultdict(list)
    for go_id, group in assignment.items():
        group_to_terms[group].append(go_id)

    output = {
        "groups":     dict(group_to_terms),
        "unassigned": list(unassigned),
    }

    with open(path, "w") as f:
        json.dump(output, f, indent=2)

    print(f"\nAssignment saved to {path}")
    print(f"  {len(group_to_terms)} groups written, {len(unassigned)} unassigned terms recorded")
    print("  This file is the input for the data processor and training scripts — keep it around.")


# ── MAIN ───────────────────────────────────────────────────────────────────────

def main():
    print("=" * 60)
    print("NeuralProt — GO Term Group Assigner")
    print("=" * 60)

    # Step 1: Load the pre-parsed GO dictionary
    go_dict = load_go_dict(GO_DICT_PATH)

    # Step 2: Rebuild the ancestor cache — needed to check group membership
    ancestor_cache = build_ancestor_cache(go_dict)

    # Step 3: Get the full ontology size of each target group
    #         This is the tiebreaker when a term belongs to multiple groups
    group_sizes = get_group_sizes(go_dict, ancestor_cache, TARGET_GROUPS)

    # Step 4: Pull out the GO terms that actually appear in our dataset
    dataset_go_terms = read_dataset_go_terms(DATASET_PATH, GO_COL_IDX, go_dict)

    # Step 5: Do the assignment — one group per term, no overlaps
    assignment, unassigned = assign_go_terms(
        dataset_go_terms, ancestor_cache, TARGET_GROUPS, group_sizes
    )

    # Step 6: Print the full breakdown so we can decide what to split or merge
    report(assignment, unassigned, group_sizes, TARGET_GROUPS)

    # Step 7: Write the result to disk for the training pipeline
    save_assignment(assignment, unassigned)

    print("\n" + "=" * 60)
    print("Done. Check the summary above — anything flagged 'SPLIT FURTHER'")
    print("needs to go through the large_group_splitter in data_processor.ipynb before training.")
    print("=" * 60)


if __name__ == "__main__":
    main()